image: python:3.8-slim

stages:
  - test
  - build
  - deploy-test
  - deploy

.unittests:
  stage: test
  script:
    - pip install -r requirements_dev.txt  # test dependencies
    - pip install -e .  # install package such that tests can find it
    - pytest --cov-report term --cov-report html:coverage-report --cov=simple_env_config

# only run on oldest and newest supported CPython version on non-master branches
.unittests-master-only:
  extends: .unittests
  only:
    - master

unittests-3.6:
  extends: .unittests
  image: python:3.6-slim

unittests-3.7:
  extends: .unittests-master-only
  image: python:3.7-slim

unittests-3.8:
  extends: .unittests-master-only
  image: python:3.8-slim

unittests-3.9:
  extends: .unittests
  image: python:3.9-slim
  artifacts:
    paths:
      - coverage-report

unittests-pypy-3.7:
  extends: .unittests-master-only
  image: pypy:3.7-slim

compare-version-and-tag:
  only:
    - tags
  stage: test
  script:
    - 'TAG_VERSION=$CI_COMMIT_REF_NAME'
    - 'PACKAGE_VERSION="v$(python version.py)"'
    - 'echo "tag:     $TAG_VERSION"'
    - 'echo "package: $PACKAGE_VERSION"'
    - 'if [ $TAG_VERSION != $PACKAGE_VERSION ]; then echo "Versions do not match!"; exit 1; fi'

build-package:
  only:
    - tags
  stage: build
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

.deploy-on-pypi-instance:
  only:
    - tags
  dependencies:
    - build-package
  script:
    - pip install
      setuptools wheel twine
    - python -m twine upload dist/*

deploy-test-pypi:
  extends: .deploy-on-pypi-instance
  stage: deploy-test
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $TEST_PYPI_API_TOKEN
    TWINE_REPOSITORY: test-pypi

deploy-pypi:
  extends: .deploy-on-pypi-instance
  stage: deploy
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_API_TOKEN
  when: manual

pages:
  stage: deploy
  dependencies:
    - unittests-3.9
  script:
      - mv coverage-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
